### ISSUE TITLE
The tool doesn't work with Python 3.5

### ISSUE THREAD

**Issue by sasadangelo** [Showmax/patroni-exporter#2]
Hi,

I am working on a monitoring solution for Patroni cluster and I would like to use this tool to export /patroni data via Prometheus interface. My env uses Python 3.5 and I think your tool, by design, uses > 3.6.

Can you take in consideration to port your code in Python 3.5? In my fork, I fixed the code to do that but I would like to port it in official code. I can do a pull request but before I want to discuss if my fixes are correct.

I am not an expert in Python and I would like to know if there is a method to deploy extra/startup-scripts directly in the right place to use the tool as a service.

**Comment by jbrunclik** [comment]
Hi @sasadangelo,

Can you please elaborate on why would you need to use an older version of Python?

The latest released version as of today is Python 3.7. So we don't see a point in adapting the exporter for an older version.

I would suggest that you update your environment to the latest Python release instead, unless there is some serious reason not to.
