### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by Ikrar-k** [Showmax/patroni-exporter#3]
./patroni_exporter.py -u ip_address:8008
  File "./patroni_exporter.py", line 34
    def __init__(self, url: str, timeout: int, verify: str):
                          ^
SyntaxError: invalid syntax

Can you please provide how to run this command as I am getting invalid syntax.

**Comment by jbrunclik** [comment]
As stated in the [README](https://github.com/Showmax/patroni-exporter/blob/master/README.md), you need to use Python >= 3.6.
