### ISSUE TITLE
Parse patroni api response even if code is 503

### ISSUE THREAD

**Issue by pkesso** [Showmax/patroni-exporter#5]
Patroni api response json still contents useful information even if HTTP code is 503, which basicly means that node is not a leader. There is a difference between "api is unavailable" and "this node is not a leader", so please do parse api response if any, regardless of HTTP code.

**Comment by zloo** [comment]
Hi @pkesso. Thank you for the issue report and a pull request.

I explored our patroni instances but was unable to find any case when patroni api responds with anything else than a "200 OK" when we scrape /patroni, which is the default. Can you maybe share more information about your setup? I'm 100% OK merging the pull request, I'm just curious about when this happens and why - maybe a version difference, a bug in your particular version, my misunderstanding or maybe you use a different endpoint than us :)

Thanks!

**Comment by pkesso** [comment]
Oh, my bad.
Truely, /patroni always returns 200, but / returns 503 on slaves. And I missed /patroni in PATRONI_URL, so there was a problem. 
I'm sorry for the trouble.

**Comment by zloo** [comment]
no worries at all! thank you very much for contacting us ;)
